//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by config.rc
//
#define IDD_PROPDISPLAY                 107
#define IDD_PROPART                     108
#define IDD_PROPMISC                    109
#define IDD_PROPSTARTSHUT               111
#define IDD_PROPHOTKEYS                 112
#define IDD_PROPLAYOUT                  113
#define IDI_LOGO                        117
#define IDD_DLGCONFIGMAIN               125
#define IDD_DLGCOLORSFONTS              126
#define IDD_DLGPOSITION                 127
#define IDD_DLGFEATURES                 128
#define IDD_PROPADVANCED                130
#define IDD_PROPSONGSEARCH              131
#define IDD_PROPRATINGS                 132
#define IDC_CHKFORCEWIDTH               1014
#define IDC_CHKQUITITUNES               1016
#define IDC_CHKPROMPTQUIT               1017
#define IDC_EDTVOLCHGINT                1018
#define IDC_CHKSTARTITUNES              1022
#define IDC_CHKSTARTWITHHOTKEYS         1023
#define IDC_CHKSTARTWINDOWS             1025
#define IDC_CHKSHOWINTRAY               1051
#define IDC_EDTINFOTIME                 1052
#define IDC_EDTINFOTIMEEND              1053
#define IDC_LSTHOTKEYS                  1054
#define IDC_EDTINFOTIMESTART            1054
#define IDC_EDTDISABLESHORT             1055
#define IDC_BTNKEYSDEFS                 1058
#define IDC_EDTOSDTEXT                  1085
#define IDC_CHKSHOWART                  1089
#define IDC_EDTITUNESTITLE              1094
#define IDC_CHKUSEFADE                  1095
#define IDC_EDTQUICKPLAYLIST            1095
#define IDC_RBARTMODE2                  1099
#define IDC_RBARTMODE3                  1100
#define IDC_EDTARTCONST                 1101
#define IDC_EDTHOTKEY                   1110
#define IDC_CHKOUTLINEMODE              1112
#define IDC_EDTCSIFORMAT                1113
#define IDC_CHKUSEVISUALS               1116
#define IDC_CHKHIDEDISPLAYITUNES        1117
#define IDC_CMBMONITOR                  1119
#define IDC_CHKQUITWITHITUNES           1120
#define IDC_CHKMISSINGTAGS              1122
#define IDC_CHKTOPMOST                  1122
#define IDC_CHKUSEFOLDERART             1122
#define IDC_CHKGROUPINGTAG              1123
#define IDC_CMBJUSTIFY                  1124
#define IDC_CMBPOSTEXT                  1125
#define IDC_EDTJUMPONEVALUE             1126
#define IDC_EDTJUMPTWOVALUE             1127
#define IDC_CMBJUMPONETYPE              1128
#define IDC_CMBJUMPTWOTYPE              1129
#define IDC_CMBCONSTANT                 1130
#define IDC_BTNINSERT                   1131
#define IDC_COLOR_BK                    1132
#define IDC_BTNCLOSE                    1132
#define IDC_COLOR_FONT                  1133
#define IDC_COLOR_BORDER                1134
#define IDC_BTNRESETALL                 1134
#define IDC_BTNEMPTYSTAR                1134
#define IDC_CHKSTARTWITHITUNES          1135
#define IDC_RDOALWAYSSHOW               1135
#define IDC_COLOR_ART                   1135
#define IDC_RDOSHOWFORX                 1136
#define IDC_COLOR_DROP                  1136
#define IDC_FONT_STYLE                  1137
#define IDC_PICPOSITION                 1141
#define IDC_SLDTRANSPARENCY             1142
#define IDC_CMBRATINGDELTA              1142
#define IDC_CMBENTERACTION              1142
#define IDC_CMBSHAPETYPE                1142
#define IDC_CMBDISPLAYSIZE              1143
#define IDC_EDTMAXSSRESULTS             1143
#define IDC_EDTFULLCHAR                 1143
#define IDC_EDTDROPSHADOWOFFSET         1143
#define IDC_EDTOFFSETBEGIN              1143
#define IDC_EDTSTATICART                1143
#define IDC_CMBBORDERWIDTH              1144
#define IDC_EDTOFFSETEND                1144
#define IDC_TRELIST                     1145
#define IDC_CMBARTBORDERWIDTH           1145
#define IDC_CHKWARNSAVECHGS             1146
#define IDC_BTNOPENCFGFLDR              1147
#define IDC_RDOSEARCHCURRENT            1148
#define IDC_RDOSEARCHLIBRARY            1149
#define IDC_CMBSHIFTACTION              1150
#define IDC_CMBCTRLACTION               1151
#define IDC_EDTCUSTOMDISPSIZE           1152
#define IDC_CHKMINIMIZEATSTART          1153
#define IDC_BTNFULLSTAR                 1155
#define IDC_BTNHALFSTAR                 1156
#define IDC_BTNAPPLY                    1157
#define IDC_RDOTEXT                     1158
#define IDC_RDOIMAGE                    1159
#define IDC_EDTHALFCHAR                 1160
#define IDC_EDTEMPTYCHAR                1161
#define IDC_CHKPROMPTTODELETE           1167
#define IDC_CHKDELETEFROMDISK           1168
#define IDC_STCFULLSTAR                 1169
#define IDC_STCHALFSTAR                 1170
#define IDC_STCEMPTYSTAR                1171
#define IDC_RDOSHAPES                   1172
#define IDC_CMBSHAPESTYLE               1173
#define IDC_STCSHAPEOUTLINE             1174
#define IDC_STCSHAPEFILL                1175
#define IDC_CHKUSEDROPSHADOW            1176
#define IDC_CHKSHOWATEND                1177
#define IDC_CHKALLOWBLANKS              1178
#define IDC_CHKSHOWATSTART              1178
#define IDC_CHKSTATICART                1179
#define IDC_BTNSTATICART                1180
#define IDC_CHKDISABLESHORTTRACKS       1181
#define IDC_CHKIGNOREACONFOCUS          1182
#define IDC_CHKEXCEPTWHENPAUSED         1182
#define IDC_CHKONLYTOGGLEREPEATONE      1183
#define IDC_RDOSINGLEMONITOR            1184
#define IDC_RDOALLMONITORS              1185
#define IDC_STATIC                      -1

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NO_MFC                     1
#define _APS_NEXT_RESOURCE_VALUE        129
#define _APS_NEXT_COMMAND_VALUE         40007
#define _APS_NEXT_CONTROL_VALUE         1186
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
